### ISSUE TITLE
How to improve performance? 

### ISSUE THREAD

**Issue by int2e** [marcoCasamento/Hangfire.Redis.StackExchange#104]
`redis server`
cpu: i3 9100
mem size: 32GB
ip: 192.168.1.2 / 10gb port

`hangfire server`
cpu: i9 10900k
mem size: 64GB
ip: 192.168.1.3 / 10gb port
workcount: 20-100 no difference 

runtime .net 5.0

The current processing speed does not exceed 2000 / s
![image](https://user-images.githubusercontent.com/18641363/105999757-02780a80-60e9-11eb-93b8-23c4125dcab1.png)

**Comment by marcoCasamento** [comment]
how many workers on that instance ? (you can see that the number on the server page)

**Comment by int2e** [comment]
> how many workers on that instance ? (you can see that the number on the server page)
workcount = 20  Can't reach 2000/s
workcount = 100 Can't reach 2000/s

![image](https://user-images.githubusercontent.com/18641363/106001972-8a5f1400-60eb-11eb-95b7-5c3d9c973577.png)

**Comment by marcoCasamento** [comment]
the number "12" you're seeing here is not an useful for such quick jobs. It represents the number of current running jobs at any given moment.
Hangfire statistics, though, are a valid point.
I've never dealt with such numbers as my job usually take at least 100ms so the server would cap way early than 2000 job/sec.
I can suggest to look at the method [FetchNextJob](https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/blob/master/Hangfire.Redis.StackExchange/RedisConnection.cs ) that along with the redis pub/sub in the [RedisScubscription](https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/blob/master/Hangfire.Redis.StackExchange/RedisSubscription.cs) is responsible of Fetching jobs.

As a mean of having a grasp of redis performance, it COULD be useful to fire up a couple of instances on the same hangfire server

However, with such a great number of jobs, it seems that you're using hangfire as a messagebus for which purpose I'd look elsewhere.

**Comment by int2e** [comment]
> the number "12" you're seeing here is not an useful indicator for such quick jobs. It represents the number of current running jobs at any given moment.
> Hangfire statistics, though, are a valid point.
> I've never dealt with such numbers as my job usually take at least 100ms so the server would cap way early than 2000 job/sec.
> I can suggest to look at the method [FetchNextJob](https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/blob/master/Hangfire.Redis.StackExchange/RedisConnection.cs) that along with the redis pub/sub in the [RedisScubscription](https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/blob/master/Hangfire.Redis.StackExchange/RedisSubscription.cs) is responsible of Fetching jobs.
> 
> As a mean of having a grasp of redis performance, it COULD be useful to fire up a couple of instances on the same hangfire server
> 
> However, with such a great number of jobs, it seems that you're using hangfire as a messagebus for which purpose I'd look elsewhere.


hi，I want to achieve 20k-200k tasks per second, I don’t think I can do it!
:)

**Comment by marcoCasamento** [comment]
I don't think either.
However, there's a paid option for redis storage directly from hangfire site, maybe that version is able to achieve better performance

**Comment by int2e** [comment]
ok, thanks!
