### ISSUE TITLE
hangfire_console:refs A large number of such keys cannot be deleted

### ISSUE THREAD

**Issue by gnahziak** [marcoCasamento/Hangfire.Redis.StackExchange#108]
![image](https://user-images.githubusercontent.com/16639887/126747240-418791bc-865e-4c5e-9754-296efe2aefee.png)
use HangFire.Redis.StackExchange 1.8.4
A large number of such keys cannot be  auto deleted

**Comment by marcoCasamento** [comment]
what do you mean ? please open a PROPER issue
