### ISSUE TITLE
How can I use batches without using the pro version?

### ISSUE THREAD

**Issue by leoutnlp** [marcoCasamento/Hangfire.Redis.StackExchange#109]
podrian darme un ejemplo de como usar batches?

**Comment by marcoCasamento** [comment]
Sorry, no, I wouldn't give a working sample.
That would possibly impact the work (and income) of hangfire's author, thus potentially impacting the development of hangfire itself and I believe no hangfire's user wants that.
You can have a look at https://stackoverflow.com/questions/34954869/how-to-handle-batch-jobs-without-hangfire-pro where the author itself gave some directions.
