### ISSUE TITLE
Consider not using the ConnectionString on .ToString()

### ISSUE THREAD

**Issue by danspark** [marcoCasamento/Hangfire.Redis.StackExchange#115]
This causes the full connection string to be logged when the server is being started:

`Starting Hangfire Server using job storage: 'redis://host.docker.internal:6379/0'`

If there is a password in the connection string, it is not filtered and it will be logged.

I don't know if there's a reason for logging it, but if there isn't, another field can be used, or the password can be filtered out.

**Comment by marcoCasamento** [comment]
I agree. What about something like
`String.Join(',', cnnString.Split(',').Where(x=> !x.Contains("password", StringComparison.InvariantCultureIgnoreCase)))` ?

**Comment by danspark** [comment]
https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/blob/7019ede12837a89ee32ebf2e3e4ee65bc4341730/Hangfire.Redis.StackExchange/RedisStorage.cs#L55

The configuration is parsed when the storage is constructed, maybe it would be better to store it and replace `ConnectionString` with `redisOptions.ToString(includePassword: false)`

**Comment by erikvojtko** [comment]
Any progress on this issue? @danspark I can't seem to find the mentioned PR.

**Comment by matheusriboli** [comment]
Hello @marcoCasamento, I opened a PR fixing this issue. Could you review it?
https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/pull/116

**Comment by glen-84** [comment]
@marcoCasamento Should this issue be closed now?

**Comment by marcoCasamento** [comment]
Absolutely. It has been merged and as far as I remember, tested.
