### ISSUE TITLE
Long Running Jobs (longer than 30 min) keep restarting

### ISSUE THREAD

**Issue by DR9885** [marcoCasamento/Hangfire.Redis.StackExchange#118]
Long Running Jobs (longer than 30 min) keep restarting. 

How can I get the jobs to run longer?

**Comment by oliveiracdz** [comment]
Did you look at InvisibilityTimeout setting from the [Hangfire docs](https://docs.hangfire.io/en/latest/configuration/using-redis.html?highlight=invisibilitytimeout#:~:text=from%20growing%20indefinitely.-,InvisibilityTimeout,-TimeSpan.FromMinutes(30)?

**Comment by DR9885** [comment]
will try this, closing for now.
