### ISSUE TITLE
Is There anyaway to change prefix(RedisStorageOptions) of RedisStorage when job is creating ? 

### ISSUE THREAD

**Issue by ltb27** [marcoCasamento/Hangfire.Redis.StackExchange#125]
Now, I want to change JobStorage prefix when job creating, but seen that RedisStorage no explore it !

**Comment by ltb27** [comment]
![image](https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/assets/96302113/0ae274ed-32db-4e3a-891a-1e51be5cb379)
![image](https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/assets/96302113/3e6bb472-6dad-40e1-886a-0e22f859f26f)
![image](https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/assets/96302113/7aa2420d-4a84-42c6-950c-5934b3d59d9a)

**Comment by Toumash** [comment]
Looks like it should be closed after closing a continuation of the issue by the same author https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/issues/127
