### ISSUE TITLE
Can you change RedisStorageOption From Private to Public 

### ISSUE THREAD

**Issue by ltb27** [marcoCasamento/Hangfire.Redis.StackExchange#127]
Now, I Want to change Prefix of job creating baseon some info like host name . but i read the source code , RedisStorage now has the access modifier is private 
![image](https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/assets/96302113/434c90bc-91b1-435f-a9db-163372e09d47)

**Comment by Toumash** [comment]
If you want to change prefix based on hostname just use already available `RedisStorageOptions.Prefix`

```
hangfireConfig.UseRedisStorage(redisSettings.ConnectionString,new RedisStorageOptions()
                    {
                        Prefix = Environment.MachineName
                    });
```

**Comment by Toumash** [comment]
Should be closed

**Comment by marcoCasamento** [comment]
right
