### ISSUE TITLE
RedisConnection bug or intended? `GetSetCount` provided key does not need `{hangfire}` perfix vs `GetSetContains` 

### ISSUE THREAD

**Issue by BobSilent** [marcoCasamento/Hangfire.Redis.StackExchange#130]
Hi,

is it a bug or by intention that some APIs in `RedisConnection` require to prefix the `key` with `{hangfire}` and others not?

E.g. 
 `GetSetCount` 
when calling the API i just use a key, the API will automatically prefix the key with `{hangfire}:`
https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/blob/5702f09e07cef6f1612e4f297e4defdd6fdeaaf0/Hangfire.Redis.StackExchange/RedisConnection.cs#L360-L363

but e.g. here:
when calling the API I explicitly need to prefix the key with `{hangfire}`
https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/blob/5702f09e07cef6f1612e4f297e4defdd6fdeaaf0/Hangfire.Redis.StackExchange/RedisConnection.cs#L130-L134

also the test is doing it explicitly:
https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/blob/5702f09e07cef6f1612e4f297e4defdd6fdeaaf0/Hangfire.Redis.Tests/RedisConnectionFacts.cs#L207-L230

And here the `GetAllItemsFromSet` which does not require the prefix:
https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/blob/5702f09e07cef6f1612e4f297e4defdd6fdeaaf0/Hangfire.Redis.Tests/RedisConnectionFacts.cs#L102-L112

**Comment by marcoCasamento** [comment]
I'd say it's a **BUG**.
If I recall correctly those methods were added to support hangfire 1.7 new Storage Extensions and I simply forgot to use the prefix, both in code and test. 
I don't know how hangfire use these new methods (and if it does at all in the core version) but I strongly suspect that if/when it will, a bug will arise.
Thanks for spotting

**Comment by BobSilent** [comment]
At least the Method `GetSetContains` is currently not used within Hangfire, but I wanted to use it ;)

@marcoCasamento  as you confirmed this as bug. I can prepare a PR if this is ok.

**Comment by marcoCasamento** [comment]
Yes, thanks.
I suppose this method is used somewhere in hangfire.pro, but I don't have that package
