### ISSUE TITLE
Does GlobalConfiguration.SetDataCompatibilityLevel affect something in Redis Storage?

### ISSUE THREAD

**Issue by FixRM** [marcoCasamento/Hangfire.Redis.StackExchange#134]
Hello, and thank for your work! Can you please answer, does GlobalConfiguration.SetDataCompatibilityLevel affect something in Redis Storage or it's only related to first party SQL Server storage?

**Comment by marcoCasamento** [comment]
There is nothing specifically tied to the storage, meaning there is no
change in the data structure, is more about how the data in the storage are
saved and retrieved, it seems serialization format has changed.
You should refer to hangfire documentation
https://docs.hangfire.io/en/latest/upgrade-guides/upgrading-to-hangfire-1.7.html
for more insight, and I haven't tried to raise the compatibility level from
it's default; for what I can say, there is nothing in the storage tied to
compatibility level.
There are instead other changes on the storage about "supported features"
by the storage, that is keep expanding and I'm working for supporting them
in these days, but that's another story.


Il ven 12 gen 2024, 06:25 Artem Grunin ***@***.***> ha
scritto:

**Comment by FixRM** [comment]
Thanks @marcoCasamento
