### ISSUE TITLE
BUG: Job queue is always default in history

### ISSUE THREAD

**Issue by Lexy2** [marcoCasamento/Hangfire.Redis.StackExchange#138]
**Steps to repro:**
1. Enqueue a job for a queue other than `default`.
2. Optionally, execute it by a server.
3. Query the monitoring API for the job status history.

**Expected:**
History data contains `"Queue": "<queue-name>"`

**Actual:**
History data contains `"Queue": "default"`

**Comment by marcoCasamento** [comment]
That's interesting and it seems clearly linked to #142. All of the monitoring API relies on GetJobsWithProperties to fetch history data, do you find the problem with all methods ? (FailedJobs, SucceededJobs, ProcessingJobs etc)

**Comment by Lexy2** [comment]
Nope, this is just for ScheduledJobs. The reason is that other states have implemented handlers in the storage.
I'll have a crack at it, the problem seems a bit deeper.

**Comment by Lexy2** [comment]
Apparently, this particular issue is not related to #137 or #142. 
The `"Queue": "default"` hash entry comes from the primary `EnqueuedState` constructor - see [Hangfire/EnqueuedState.cs](https://github.com/HangfireIO/Hangfire/blob/main/src/Hangfire.Core/States/EnqueuedState.cs#L90) and is set to `default` regardless of what's specified in the job.
However, this value is used if the job does not specify a queue (i.e. storage doesn't support `Queue` property, or `Enqueue` is called without specifying the queue explicitly).

We could potentially implement an `EnqueuedStateHandler` that would strip this property from the state to avoid confusion. But I'm not sure how this is used in the wild - maybe `QueueAttribute` depends on it and such?
With the fix of #137 I'm happy to just ignore this issue.
