### ISSUE TITLE
failover causes a crash during redis cluster upgrade

### ISSUE THREAD

**Issue by erikkkwu** [marcoCasamento/Hangfire.Redis.StackExchange#155]
during the Redis cluster upgrade, we noticed that Hangfire continuously tries to connect to the machine that has been taken down, causing all jobs to stop. I found that these two commits ([fd68e86](https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/commit/fd68e86c21843c56ab48dedb2e933f4dc9e00ec1) , [cd5ae9a](https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/commit/cd5ae9ae88f9546fc2cf389f00d556073aab983f)) address this issue, and our own testing shows that it works. However, these fixes are included in a beta version with a large number of other commits, so we're hesitant to use it in production. Could you release a version specifically to address this issue ?

**Comment by marcoCasamento** [comment]
So you made a checkout at [fd68e86c](https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/commit/fd68e86c21843c56ab48dedb2e933f4dc9e00ec1) and it works ?

**Comment by erikkkwu** [comment]
we only picked these two commits separately for testing. we actually ran the failover process in our test environment, and it worked fine.

**Comment by marcoCasamento** [comment]
I'm afraid that cherry picking would make a mess in the history. I also believe that the problem arise with rel 1.9.5 were introduced by 1a7c7ad7 , but I didn't verify that.
If you can try checkout at fd68e86c, I could branch at that version and publish an updated package

**Comment by erikkkwu** [comment]
@marcoCasamento after our testing, everything seems to be working fine !

**Comment by marcoCasamento** [comment]
Great news! 
Expect an updated package today then, keep you posted

**Comment by erikkkwu** [comment]
thank you so much!
