### ISSUE TITLE
have any plan to upgrade hangfire v1.5.0?

### ISSUE THREAD

**Issue by xyting** [marcoCasamento/Hangfire.Redis.StackExchange#16]
hangfire v1.5.0 had released, and many API had changed, are you have any plan to support hangfire v1.5.0?

**Comment by marcoCasamento** [comment]
I didn't update my local version to HF 1.5 yet, but I didn't see changes to the Storage API.
What kind of issues do you encounter with the actual version of Hangfire.Redis.StackExchange and Hangfire.Core 1.5 ?

**Comment by jamesjhhan** [comment]
Seems to work fine for me.
