### ISSUE TITLE
Nuget package dependencies

### ISSUE THREAD

**Issue by zlangner** [marcoCasamento/Hangfire.Redis.StackExchange#21]
HangFire.Core is dependent on Newtonsoft.Json >= 5.0.0. Why is this package dependent on Newtonsoft.Json >= 6.0.8? Wouldn't it be best to keep the dependencies in this package in line with those of HangFire.Core?

**Comment by marcoCasamento** [comment]
Yes probably it would. I'm not sure about why it was updated though. Have you tried to use ver 5 ?

**Comment by zlangner** [comment]
I have not. Though I have gotten it working with 6.0.5 (the version my solution already had) by reverting all the json.net updates that Nuget performs after installing this package. This is quite the hassle if I have to keep doing that every time this package is updated. 

Since it seems like there is no reason for this package to have a tighter restriction I'll put together a pull request later today align this with Hangfire.Core, that way any future updates to this package won't cause a Nuget nightmare for anyone unlucky enough to not be on the latest Newtonsoft package.

**Comment by marcoCasamento** [comment]
I believe that this can now be closed, just lowered and aligned newtonsoft.json to hangfire.core
