### ISSUE TITLE
Pass in ConnectionMultiplexer instance

### ISSUE THREAD

**Issue by sjwoodard** [marcoCasamento/Hangfire.Redis.StackExchange#23]
I'm using Azure Redis, and it requires to use a single ConnectionMultiplexer, but your library creates its own instance. This is a problem because I need to use Redis in other parts of my application.

It looks like I could just create a new constructor in RedisStorage that would allow me to pass in my own ConnectionMultiplexer. I'm going to fork and if interested I will submit a PR. Thanks.

**Comment by marcoCasamento** [comment]
I'm sorry for this PR I've simply forgot about it, I've nevertheless implemented the changes you did, (couldn't merge the PR as it was since the codebase changed meanwhile).
Could we close it ?
