### ISSUE TITLE
Failed restore package with ASP.NET Core project

### ISSUE THREAD

**Issue by tsu1980** [marcoCasamento/Hangfire.Redis.StackExchange#25]
Bacause package name in nuspec is wrong IMO.

Current:

```
<dependency id="HangFire.Core" version="1.5.4" />
```

Shoud be:

```
<dependency id="Hangfire.Core" version="1.5.4" />
```

I faced a problem that cannot restore package. please see https://github.com/dotnet/cli/issues/236

I created a new project with ASP.NET Core Web Application(.NET Framework) RC2, `Install-Package Hangfire.Redis.StackExchange`. the error occured.

**Comment by marcoCasamento** [comment]
The issue at https://github.com/dotnet/cli/issues/236 has been closed, do you still experience the problem?

**Comment by tsu1980** [comment]
I think the issue has gone. I created a new project and `Install-Package Hangfire.Redis.StackExchange -Version 1.4.5` again, but works fine. I will close this ticket. Thankyou for response!
