### ISSUE TITLE
Default Db from ConnectionString is ignored

### ISSUE THREAD

**Issue by zivillian** [marcoCasamento/Hangfire.Redis.StackExchange#26]
The StackExchange.Redis Connectionstring allows to specify the default db id ([Documentation](https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Configuration.md#user-content-configuration-options)). This option is currently overwritten by the default value (0) by RedisStorageOptions.

**Comment by marcoCasamento** [comment]
Could this be closed now ?
