### ISSUE TITLE
How to use in .net core?

### ISSUE THREAD

**Issue by dotnetshadow** [marcoCasamento/Hangfire.Redis.StackExchange#36]
Great work on the project, is there a guide on how to use this library in .net core?

![error](https://cloud.githubusercontent.com/assets/296247/20999822/5874e3e8-bd6b-11e6-9203-03c72ad4142d.PNG)

I seem to be getting an error where it can't find the method UseRedisStorage()?

Does this work without Pro?

It might be worth having a page where you can show various configuration settings, which I found through closed issues:

`GlobalConfiguration.Configuration.UseDashboardMetric(
            storage.GetDashboardMetricFromRedisInfo("Redis Version", RedisInfoKeys.redis_version)
            );`

**Comment by dyfilatov** [comment]
Same as .net framework, I guess.
`        public void Configuration(IAppBuilder app)
        {
            RedisStorage storage = new RedisStorage("localhost:6379");
            GlobalConfiguration
                .Configuration
                .Use<JobStorage>(storage, jobStorage => {})
                .UseDefaultActivator();
            JobStorage.Current = storage;
            app.UseHangfireDashboard();
            app.UseHangfireServer();
        }`

**Comment by dotnetshadow** [comment]
Thanks for that

**Comment by marcoCasamento** [comment]
Yes, I agree some guide are always useful, also some extension methods as you referred in #39 would be nice too. Let's see if I can arrange something
