### ISSUE TITLE
Does SucceededListSize and DeletedListSize work?

### ISSUE THREAD

**Issue by dotnetshadow** [marcoCasamento/Hangfire.Redis.StackExchange#38]
Hi there

I recently implemented the Redis connection as:
```
var storage = new RedisStorage("127.0.0.1:6379,abortConnect=false", new RedisStorageOptions { Db = 1, Prefix = "hangfire:app1:", InvisibilityTimeout = TimeSpan.FromMinutes(10), SucceededListSize = 10, DeletedListSize = 10 });
```
But it seems that it doesn't have an effect, the list always keeps showing more than 10 items, even though my items have expired

![jobs](https://cloud.githubusercontent.com/assets/296247/21212703/480be22c-c2e3-11e6-88c8-614602dbda7f.PNG)

I know that the sqlstorage has a property called JobExpirationCheckInterval which check every 30 mins, but I'm not sure if the Redis implementation has something similar or if the ExpirationManager is actually being called at all?

**EDIT:**
I just created over 500 jobs and it looks like it's capping at 500, so I'm not sure why my settings above aren't taking effect.

**Comment by marcoCasamento** [comment]
You're right there's a bug and no test for it.

**Comment by marcoCasamento** [comment]
#56 by @pieceofsummer  solves this. Please have a look, I'm going to close this for now
