### ISSUE TITLE
Can be used in production?

### ISSUE THREAD

**Issue by robertmircea** [marcoCasamento/Hangfire.Redis.StackExchange#4]
Hi,

I would like to use this library in a project.

Is it ready for production use? Do you still consider it still as work in progress? Are there any known issues?

Thanks!

**Comment by marcoCasamento** [comment]
Hi,

I actually do use it in three different production environments (two servers each, processing between 1k-15k short jobs/hour and 5/10 long jobs/hour). 

No serious issues so far, but I’ve been noticed that it sometimes raise an error when calling the MonitoringApi (KeyNotFoundException), but didn’t have time to excatly spot the error. It definetely Worth investigating and fixing it, but a retry makes the error go away.



There are no other known issues, by the moment.


Regards,

Marco Casamento



Da: Robert Mircea
Data invio: ‎sabato‎ ‎25‎ ‎aprile‎ ‎2015 ‎18‎:‎31
A: marcoCasamento/Hangfire.Redis.StackExchange





Hi,

I would like to use this library in a project.

Is it ready for production use? Do you still consider it still as work in progress? Are there any known issues?

Thanks!
