### ISSUE TITLE
Library cannot be used alongside Microsoft.Extensions.Caching.Redis

### ISSUE THREAD

**Issue by ryanelian** [marcoCasamento/Hangfire.Redis.StackExchange#49]
https://www.nuget.org/packages/Microsoft.Extensions.Caching.Redis/

First, thank you for merging https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/pull/48

Unfortunately my critical concern about the library being unusable with `Microsoft.Extensions.Caching.Redis` is still not resolved, hence the reason behind the creation of this separate issue.

## Description

`Microsoft.Extensions.Caching.Redis` library is being used by ASP.NET Core MVC to perform caching to distributed cache using `StackExchange.Redis.StrongName`.

The reason that you **need** this particular library when working with Redis using ASP.NET Core MVC is because it enables you to use `Session` and `TempData` for users but stored into Redis instead of in-memory. (Eases development using load-balanced architecture)

Unfortunately `Hangfire.Redis.StackExchange` as of latest version 1.7.0 is still dependent on `StackExchange.Redis`, which prevents this library from being used alongside 
`Microsoft.Extensions.Caching.Redis`...

## Solution

Reiterating what I've written before in the merge request page, there are 3 solutions to this particular problem:

1. Change the dependency of `Hangfire.Redis.StackExchange` itself to `StackExchange.Redis.StrongName`. In the future, when `Hangfire.Core` is signed, we can sign `Hangfire.Redis.StackExchange` so it's signed by default. (Hence no need for separate strong-named package)

2. Insist on uploading the `Hangfire.Redis.StackExchange.StrongName` package but do not sign it. (Because it **will not** run due to `Hangfire.Core` not yet signed) While this is misleading and may upset people who want a strongly named package of this project, it enables it to be used alongside `Microsoft.Extensions.Caching.Redis` for now. (At the same time, reserving the package name in nuget.org)

3. Creating an alternate package `Hangfire.Redis.StackExchange.Alternative` that depends on `StackExchange.Redis.StrongName` instead of `StackExchange.Redis`. Although feasible, I personally won't recommend this because it may cause confusion.

**I highly recommend approach (1).**

Can we have `Hangfire.Redis.StackExchange` version 1.7.1 or above with `StackExchange.Redis.StrongName`, please? So I don't have to do `add reference` manually to this project source directly in my solution. 💀 

I promise I'll add documentation of how to setup this with ASP.NET Core MVC on README later if you do me this favor *wink wink*.

**Comment by marcoCasamento** [comment]
I was going to write you in order to ask you to move the PR comment to a new Issue 😄 

Going with solution 1 imply that the actual userbase that use StackExchange.Redis must switch to StackExchange.Redis.StrongName, and that's not sure that they could (as an example I can't, giving that I'm using other libraries that depends on the non strong named version)

I'd go for solution 2, but I miss the point about the signing of Hangfire.Core. Are you 100% sure it need to be signed ?

**Comment by ryanelian** [comment]
> I'd go for solution 2, but I miss the point about the signing of Hangfire.Core. Are you 100% sure it need to be signed ?

100% sure, unfortunately.

Because I tried our signed `Hangfire.Redis.StackExchange.StrongName` library and it explodes spectacularly when the project is run, with an exception message like: `Referenced assembly 'Hangfire.Core' does not have a strong name`.

**Comment by marcoCasamento** [comment]
Oh, right, sure Hangfire.Redis.StackExchange DEPENDS on Hangfire.Core (among others) and every dependency must be signed.
And what about taking care of il disassembling - signing the unsigned dependency  and go for route 2 ?
Someone else seems has took this route http://stackoverflow.com/questions/331520/how-to-fix-referenced-assembly-does-not-have-a-strong-name-error/19459609#19459609

**Comment by ryanelian** [comment]
Personally, I'd rather bug the Hangfire team to release strongly-named dependencies, rather than hurting ourselves by signing the `Hangfire.Core` library manually.

We can go route 2 without signing our `StrongName` package by commenting these lines from the csproj.

```xml
<SignAssembly>True</SignAssembly>
<AssemblyOriginatorKeyFile>Hangfire_Redis_StackExchange.snk</AssemblyOriginatorKeyFile>
```

Then later when the Hangfire team signs the `Hangfire.Core` package, we'll just add those lines back.

----

Alternatively, if you really want to add more busyness into your life / really hurt yourself, you can sign the assemblies inside `Hangfire.Core`, upload as `Hangfire.Core.StrongName` to nuget.org, make our `Hangfire.Redis.StackExchange.StrongName` package depends on it, and voila.

**Comment by marcoCasamento** [comment]
No, you're right, though deassembling/signing/reassembling works fine locally, it's hard to automate and keep it running.

Let's try to beg the Hangfire.Core team in order to have a signed version. It seems there be an old thread that we could resume: https://discuss.hangfire.io/t/please-add-strong-names-to-hangfire-assemblies/339 

In the meanwhile I've seen that you took the name from Nuget, thanks.

**Comment by marcoCasamento** [comment]
added a reply on that thread: https://discuss.hangfire.io/t/please-add-strong-names-to-hangfire-assemblies/339/15?u=marcocasamento

**Comment by ryanelian** [comment]
I'll just close this issue then, since the primary problem for my project team is solved for now.

You're welcome~
