### ISSUE TITLE
Problem with connection to redis server by ip address

### ISSUE THREAD

**Issue by nicolasguenther** [marcoCasamento/Hangfire.Redis.StackExchange#5]
I'm trying to connect to a redis server on another machine by passing the ip address as the connection string: 

`new RedisStorage("192.168.178.20:6379");`

Sadly it fails with a socket exception "No such host is known". I browsed your code and realized it is trying to get a hostname for the ip address with `Dns.GetHostEntry`. Such a hostname can not be found in my network setup, but i think that shouldn't be a problem.

**Comment by nicolasguenther** [comment]
I'm still struggling with this issue. Has anyone ever been able to connect a redis server other than localhost with this library?

**Comment by marcoCasamento** [comment]
Sure, do you have a repro ?

**Comment by marcoCasamento** [comment]
Nevermind, I understood the problem with the DNS. I'll release a patch shortly

**Comment by marcoCasamento** [comment]
that should works now, can you check ?

**Comment by nicolasguenther** [comment]
Works like a charm! Thank you very much!
