### ISSUE TITLE
Tutorial for using Hangfire on Redis on ASP.NET MVC, Global.ascx, IIS, WINDOW SERVER 2012

### ISSUE THREAD

**Issue by hungud** [marcoCasamento/Hangfire.Redis.StackExchange#53]
Please write tutorial, I'm using Asp.net MVC , that it's diffrent asp.net core mvc. That it use global.ascx, it don't use OWIN

Thanks for your reading 👍

**Comment by Toumash** [comment]
Should be closed as there are no additional votes here

**Comment by marcoCasamento** [comment]
agree, tx
