### ISSUE TITLE
Request/ Question: LIFO support

### ISSUE THREAD

**Issue by AndreSteenbergen** [marcoCasamento/Hangfire.Redis.StackExchange#59]
I would like to perform actions on a LIFO basis for some queues.

What functions would I need to change and how?

**Comment by pieceofsummer** [comment]
You probably need to change https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/blob/423df3ce320ec6f2cb51ef6cd314ed4b422c1b4b/Hangfire.Redis.StackExchange/RedisWriteOnlyTransaction.cs#L164 to `ListRightPushAsync`, depending on `queue` argument.

**Comment by AndreSteenbergen** [comment]
Thanks, will try to change according to my needs. I guess I will add something in the config as well, to make it optional.
