### ISSUE TITLE
Mono support

### ISSUE THREAD

**Issue by VoidMonk** [marcoCasamento/Hangfire.Redis.StackExchange#60]
Hi, how do I go about using this lib on Mono, considering that the upstream StackExchange.Redis lib doesn't support a universal assembly for Mono (https://github.com/StackExchange/StackExchange.Redis/pull/314)?

I suppose if I reference this package via nuget, then it won't work when deployed to run on Mono/Linux, because the lib is a non-Mono build. How can I easily reference & deploy a platform specific package, so that it can seamlessly work on Windows and Linux?

**Comment by pieceofsummer** [comment]
The most reliable (and supported) way to work both on Windows and Linux is to switch to .NET Core :)

**Comment by martynfrank** [comment]
This is now a nuget package to achieve this - https://www.nuget.org/packages/Hangfire.Redis.StackExchange.Mono/1.7.1

**Comment by marcoCasamento** [comment]
Great!
Thanks!

Da: Martyn Frank
Inviato: mercoledì 6 dicembre 2017 15:00
A: marcoCasamento/Hangfire.Redis.StackExchange
Cc: Subscribed
Oggetto: Re: [marcoCasamento/Hangfire.Redis.StackExchange] Mono support (#60)

This is now a nuget package to achieve this - https://www.nuget.org/packages/Hangfire.Redis.StackExchange.Mono/1.7.1
