### ISSUE TITLE
Throw DistributedLockTimeoutException instead of TimeoutException inside RedisLock/RedisConnection.

### ISSUE THREAD

**Issue by unicrus** [marcoCasamento/Hangfire.Redis.StackExchange#61]
The method RedisConnection.AcquireDistributedLock and constructor of the RedisLock should throw DistributedLockTimeoutException instead of System.TimeoutException. See https://github.com/HangfireIO/Hangfire/pull/789 for details.

**Comment by marcoCasamento** [comment]
I guess this is very old and just need to be closed. The Acquire method raise a `DistributedLockTimeoutException`
