### ISSUE TITLE
Multiple Dashboards

### ISSUE THREAD

**Issue by aeb-dev** [marcoCasamento/Hangfire.Redis.StackExchange#62]
http://docs.hangfire.io/en/latest/configuration/using-dashboard.html#multiple-dashboards as mentioned here I would like to use multiple dashboards. However, it seems like one redis option overrides the other. I can visualize both UI but jobs listed always belong to the second prefix. Is it not supported or something else is going on? Any ideas?

This is how I register dashboards

    public static void UseHangfireDashboardWithSettings(this IApplicationBuilder app)
    {
        var redis = app.ApplicationServices.GetRequiredService<IRedisManager>().GetConfigurationOptions();
        var connectionString = redis.ToString();

        app.UseHangfireDashboard(
            pathMatch: "/jobs1",
            options: new DashboardOptions
            {
                AppPath = "/",
                Authorization = new[] { new HangfireDashboardAuthorizationFilter() },
            },
            storage: new RedisStorage(connectionString, new RedisStorageOptions
            {
                Prefix = "hangfire1:",
                InvisibilityTimeout = TimeSpan.FromMinutes(30),
                FetchTimeout = TimeSpan.FromMinutes(3),
                Db = redis.DefaultDatabase.GetValueOrDefault(),
                SucceededListSize = 499,
                DeletedListSize = 499
            })
        );

        app.UseHangfireDashboard(
            pathMatch: "/jobs2",
            options: new DashboardOptions
            {
                AppPath = "/",
                Authorization = new[] { new HangfireDashboardAuthorizationFilter() },
            },
            storage: new RedisStorage(connectionString, new RedisStorageOptions
            {
                Prefix = "hangfire2:",
                InvisibilityTimeout = TimeSpan.FromMinutes(30),
                FetchTimeout = TimeSpan.FromMinutes(3),
                Db = redis.DefaultDatabase.GetValueOrDefault(),
                SucceededListSize = 499,
                DeletedListSize = 499
            })
        );
    }

and this is how I register RedisStorage before registering dashboard

    public static class ServiceCollectionExtensions
    {
         public static void AddHangfireForRedis(this IServiceCollection services)
         {
             services.AddHangfire(configuration => configuration.UseRedisStorage());
         }
    }

**Comment by marcoCasamento** [comment]
Uh, I was not aware of such possibility, serving multiple dashboard from
one server.
I'll definitely take a look into. There's also a quite big refactor in a PR
(that it's working) and possibly could solve the problem.

I'll have a look into that soon!

Il 21 ago 2017 10:27 AM, "Ahmet Enes Bayraktar" <notifications@github.com>
ha scritto:

**Comment by MrMuMu** [comment]
Any updates so far?

**Comment by pieceofsummer** [comment]
@MrMuMu the current code does support that already. It is not published to NuGet yet, but you can build from sources and use it.

**Comment by Toumash** [comment]
Should be closed
