### ISSUE TITLE
New Nuget version?

### ISSUE THREAD

**Issue by gienec** [marcoCasamento/Hangfire.Redis.StackExchange#66]
A lot of changes were merged. Maybe It's time for new Nuget version?

**Comment by gienec** [comment]
Marco, it would be great to get newest version of Nuget :)
I'm sure many or at least 3 of us are waiting for it :)

**Comment by marcoCasamento** [comment]
Sorry, you're right, really hope to do it tomorrow 😉

Il 12 ott 2017 7:29 PM, "gienec" <notifications@github.com> ha scritto:

**Comment by gienec** [comment]
Great!
Thank you! 👍

**Comment by gienec** [comment]
Any news?
