### ISSUE TITLE
Timeout performing EXEC

### ISSUE THREAD

**Issue by caopengfei** [marcoCasamento/Hangfire.Redis.StackExchange#74]
Timeout performing EXEC, inst: 29, queue: 461, qu: 1, qs: 460, qc: 0, wr: 0, wq: 1, in: 6967, ar: 0, clientName: , serverEndpoint: Unspecified/r-uf6b854e54422e94.redis.rds.aliyuncs.com:6379, keyHashSlot: 4131 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)

**Comment by marcoCasamento** [comment]
no response on this, can it be closed?
