### ISSUE TITLE
Upgrade to StackExchange.Redis v2

### ISSUE THREAD

**Issue by bartcoppens** [marcoCasamento/Hangfire.Redis.StackExchange#77]
The library depends on version 1.2.6 of StackExchange.Redis
This makes it incompatible with a coebase that is upgraded to StackExchange.Redis v2.

**Comment by marcoCasamento** [comment]
Right, could you point out any breaking change in the 2.0 ?

**Comment by marcoCasamento** [comment]
Nevermind, just found this https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes

**Comment by bartcoppens** [comment]
Here are the breaking changes:
https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/ReleaseNotes.md

I compiled it against the new version and everything seems to work fine.

**Comment by marcoCasamento** [comment]
and it could be the right time to fix #73 giving that now the only version of stackexchange.redis is strong-named. 
But we should also upgrade the target framework, so sticking users that can't upgrade to netstandard20 or net461 to the actual version, right ?

**Comment by bartcoppens** [comment]
I agree, although I don’t have much experience with best practices on how to do this for a package like this.

**Comment by neyromant** [comment]
#78

**Comment by cuibty** [comment]
@marcoCasamento Any timeline on when can this be released? Thanks!

**Comment by petekcchen** [comment]
Any update on the new package release? I'm keen to upgrade too.

**Comment by johnmwright** [comment]
I believe this can be closed, since https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/pull/78 merged in the change and v1.8.0 in NuGet includes the change, per the release notes: https://www.nuget.org/packages/HangFire.Redis.StackExchange/1.8.0
