### ISSUE TITLE
Remove Newtonsoft

### ISSUE THREAD

**Issue by imperugo** [marcoCasamento/Hangfire.Redis.StackExchange#83]
Hi, 
what do you think to remove Newtonsoft from your dependencies and use https://github.com/facebook-csharp-sdk/simple-json instead (it's just a css class that you can copy into your package)?

This could be good in order to prevent conflict with different Newtonsoft dependencies.
Does it make sense to you? PR?

**Comment by marcoCasamento** [comment]
Sorry I've dedicated very little to nothing to this project. 
It's a great idea, I didn't even know of this project and yet newtonsoft has often bugged me and I usually go with assembly binding... where possible. thanks for the input. I can try to do the change myself but if you're still willing to make a PR it's more than welcome

**Comment by neyromant** [comment]
@marcoCasamento seems like Newtontonsoft.Json was added to deps but didn't use.
I made PR for remove it https://github.com/marcoCasamento/Hangfire.Redis.StackExchange/pull/93
