### ISSUE TITLE
can i clear all data?

### ISSUE THREAD

**Issue by moxixuan** [marcoCasamento/Hangfire.Redis.StackExchange#97]
hi,
![图片](https://user-images.githubusercontent.com/19483437/84111661-007a1200-aa5a-11ea-968e-eae206885b83.png)
i want to clear all of this data immediately.
how can i do?

**Comment by nicholashead** [comment]
@moxixuan You'd want to clear the Hangfire namespace in your Redis server.

**Comment by marcoCasamento** [comment]
exactly, or whatever namespace you've configured in RedisStorageOptions.Prefix
